---
# example upgrade from repo
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: zitadel-install
  generateName: zitadel-install-
spec:
  serviceAccountName: tekton-deployer
  taskRef:
    name: helm-upgrade-from-repo
    kind: ClusterTask 
  params:
  - name: chart_name
    value: zitadel
  - name: helm_repo
    value: http://46.246.44.41:8080
  - name: release_version
    value: v1.0.0
  - name: release_name
    value: zitadel-install
  - name: release_namespace
    value: tekton-deployer
  - name: overwrite_values
    value: autoscaling.enabled=true,autoscaling.maxReplicas=3
