---
# example upgrade from repo
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: yugabyte-install
  generateName: yugabyte-install- 
spec:
  serviceAccountName: tekton-deployer
  taskRef:
    name: helm-upgrade-from-repo
    kind: ClusterTask 
  params:
  - name: chart_name
    value: chartmuseum/database
  - name: helm_repo
    value: http://46.246.44.41:8080
  - name: release_version
    value: v1.0.0
  - name: release_name
    value: yugabyte-install
  - name: release_namespace
    value: tekton-deployer
  - name: overwrite_values
    value: storage.ephemeral=true,yugabyte.resource.master.requests.cpu=0.5,yugabyte.resource.master.requests.memory=0.5Gi,yugabyte.resource.tserver.requests.cpu=0.5,yugabyte.resource.tserver.requests.memory=0.5Gi,yugabyte.replicas.master=1,yugabyte.replicas.tserver=1
